### ISSUE TITLE
Somente o primeiro arquivo dos alias carregava

### ISSUE THREAD

**Issue by eunael** [thiagomeloo/myalias#2]
Independente de quantos comandos eram adicionados, o único que ficava executável era o comando do respectivo primeiro arquivo da pasta dos alias. Ex.: se criar o comando `test00` e o `teste01`, conseguia executar apenas o test00, enquanto o test01 não era reconhecido como comando.
O que fiz para resolver até o momento foi iterar os arquivos da pasta e carregar os arquivos um por um no `.zshrc`. Porém, não sei se é a melhor forma.
```shell
if [ "$(ls -A /home/natanael/.myalias/aliases/)" ]; then	
	for arquivo in /home/natanael/.myalias/aliases/*; do
    	if [ -f "$arquivo" ]; then
        	source "$arquivo"
    	fi
	done
fi
```

**Comment by thiagomeloo** [comment]
@naelallves após att para a versão 0.1.2 remove o código citado a cima e roda o comando `myalias setup` para recriar as configs e corrigir o problema.

para att basta executar o comando a seguir: `pip install myalias --upgrade`
